# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.isUS", false);
user_pref("browser.slowStartup.averageTime", 21073);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150126171358");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.uitour.treatment.srch-chg-action", "ViewPage");
user_pref("browser.uitour.treatment.srch-chg-treatment", "firstrun_otherDefault");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1423901970808");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1423815570808");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 20525);
user_pref("datareporting.sessions.current.main", 17285);
user_pref("datareporting.sessions.current.sessionRestored", 21158);
user_pref("datareporting.sessions.current.startTime", "1423815552865");
user_pref("datareporting.sessions.current.totalTime", 31);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1422607038000,\"mt\":1422293685000}}}");
user_pref("gecko.buildID", "20150126171358");
user_pref("gecko.mstone", "35.0.1");
user_pref("loop.soft_start_ticket_number", 15440827);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1423815570);
user_pref("toolkit.telemetry.previousBuildID", "20150126171358");
