# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1426236467);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1426236587);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1426235749);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1426236280);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1426236160);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 26);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "AU");
user_pref("browser.search.region", "AU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150224222119");
user_pref("browser.slowStartup.averageTime", 1253);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150224222119");
user_pref("browser.startup.homepage_override.mstone", "36.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1426322029264");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1426235690901");
user_pref("datareporting.policy.firstRunTime", "1426235629264");
user_pref("datareporting.sessions.current.activeTicks", 35);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 530);
user_pref("datareporting.sessions.current.main", 22);
user_pref("datareporting.sessions.current.sessionRestored", 702);
user_pref("datareporting.sessions.current.startTime", "1426236347110");
user_pref("datareporting.sessions.current.totalTime", 499);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1426235628938,\"a\":4,\"t\":141,\"c\":true,\"m\":23,\"fp\":1724,\"sr\":1945}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1426236039555,\"a\":18,\"t\":269,\"c\":true,\"m\":49,\"fp\":1162,\"sr\":1260}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"36.0\",\"DEVTOOLS_NETMONITOR_OPENED_PER_USER_FLAG\":\"36.0\"}");
user_pref("devtools.toolbox.selectedTool", "netmonitor");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:36.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1426236468);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150106.01");
user_pref("extensions.lastAppVersion", "36.0");
user_pref("extensions.lastPlatformVersion", "36.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"36.0\",\"st\":1426230247000,\"mt\":1424817926000}}}");
user_pref("gecko.buildID", "20150224222119");
user_pref("gecko.mstone", "36.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1426235693);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1426235692);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 100124);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1426236347);
user_pref("toolkit.telemetry.previousBuildID", "20150224222119");
